### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by songtianhui** [votchallenge/toolkit#100] opened 2023-05-28 12:24 UTC
I try to run vot evaluation and use NCCTracker as toturial, and meet error `Cannot allocate memory`.
My memory is over 200G which should be enough?

**Comment by songtianhui** [comment] 2023-05-28 12:30
The tracker integration is the same as https://github.com/votchallenge/integration/blob/master/python/ncc_multiobject_mask.py

**Comment by alanlukezic** [comment] 2023-05-29 08:12
Hi, this is really strange. Can you provide more information about the issue? Which version of the toolkit are you using? Which version of the trax library are you using? On which command do you get this issue? How did you initialize the workspace?

**Comment by lukacu** [comment] 2023-05-30 10:36
We will need more info on this, otherwise I will close the issue.

**Comment by songtianhui** [comment] 2023-05-31 04:53
For more information, the toolkit integration is the same as https://github.com/votchallenge/integration/blob/master/python/vot.py and https://github.com/votchallenge/integration/blob/master/python/ncc_multiobject_mask.py.
These are all the code.
And error message is shown below:
![微信图片编辑_20230531124854](https://github.com/votchallenge/toolkit/assets/77977134/b71f82d9-875a-4786-b7fb-17ef6fe2ba48)

**Comment by lukacu** [comment] 2023-05-31 07:27
The problem is very likely related to a nasty libtrax memory allocation bug that is only noticeable when the tracker is sending back  segmentation masks. It is fixed in Trax version 4.0.1. We are also releasing toolkit version 0.6.4 today that contains several performance improvements.

**Comment by songtianhui** [comment] 2023-05-31 07:33
Coool! Thanks very much for your help! I will try it soon.

**Comment by lukacu** [comment] 2023-06-04 19:38
Please close the issue if your issue was resolved.

**Closed** 2023-06-06 19:20 UTC
